### PR TITLE
Fixed issues with the tabbed module

### LINKED ISSUE #60: Tabbed pick with dmenu doesn't work
I also tried passing in the dmenu arguement, but that didn't help - so that's not the issue

### PR DESCRIPTION
**Pull request by Kasper24**
Closes #60

### CODE REVIEW

**Comment by HeavyRain266** [comment]
Could you merge those 5 commits? and in some places you have just added trailing spaces :thinking:

**Comment by Kasper24** [comment]
You can squash them when merging. Yeah, my editor removed those somehow, even tho I didn't commit that it made it's way into the PR so I added those back in to make it easily merg-able

File: module/tabbed.lua [hunk 1]
```diff
@@ -102,22 +102,21 @@ tabbed.pick_with_dmenu = function(dmenu_command)
     local list_clients = {}
     local list_clients_string = ""
     for idx, c in ipairs(t:clients()) do
-        if not c.bling_tabbed then
```
Comment (Nooo37) [inline module/tabbed.lua:105]: Wrap that part into a `if c.window ~= client.focus.window then` so that the window to which a client is added doesn't show up in the dmenu itself as that is confusing when picking

**Review by Nooo37 — CHANGES_REQUESTED** [review]
One tiny thing to change. Looks and works great otherwise, thanks :+1:
